import { jsonResult } from './result.js';
import {
  searchMetadataDef, handleSearchMetadata,
  searchMessageBodiesDef, handleSearchMessageBodies,
  semanticSearchMessagesDef, handleSemanticSearchMessages,
} from './searchTools.js';
import {
  getMessageDef, handleGetMessage,
  listMessagesDef, handleListMessages,
  getStatsDef, handleGetStats,
  aggregateDef, handleAggregate,
  searchByDomainsDef, handleSearchByDomains,
  findSimilarMessagesDef, handleFindSimilarMessages,
  searchInMessageDef, handleSearchInMessage,
  stageDeletionDef, handleStageDeletion,
} from './messageTools.js';
import {
  createDraftDef, handleCreateDraft,
  updateDraftDef, handleUpdateDraft,
  listDraftsDef, handleListDrafts,
  getDraftDef, handleGetDraft,
  deleteDraftDef, handleDeleteDraft,
} from './draftTools.js';
import {
  sendEmailDef, handleSendEmail,
  sendDraftDef, handleSendDraft,
  unsendEmailDef, handleUnsendEmail,
  listOutboxDef, handleListOutbox,
  recallEmailDef, handleRecallEmail,
} from './sendTools.js';
import {
  replyEmailDef, handleReplyEmail,
  replyAllEmailDef, handleReplyAllEmail,
  forwardEmailDef, handleForwardEmail,
} from './composeTools.js';
import {
  listFoldersDef, handleListFolders,
  createFolderDef, handleCreateFolder,
  renameFolderDef, handleRenameFolder,
  deleteFolderDef, handleDeleteFolder,
  moveMessagesDef, handleMoveMessages,
  archiveMessagesDef, handleArchiveMessages,
  trashMessagesDef, handleTrashMessages,
  markReadDef, handleMarkRead,
  markUnreadDef, handleMarkUnread,
  starMessageDef, handleStarMessage,
  unstarMessageDef, handleUnstarMessage,
  markSpamDef, handleMarkSpam,
  markNotSpamDef, handleMarkNotSpam,
  snoozeMessageDef, handleSnoozeMessage,
  unsnoozeMessageDef, handleUnsnoozeMessage,
  setCategoryDef, handleSetCategory,
  gtdClassifyDef, handleGtdClassify,
  gtdDoneDef, handleGtdDone,
} from './mailboxTools.js';
import {
  markTriagedDef, handleMarkTriaged,
  triageInboxDef, handleTriageInbox,
  getTriageContextDef, handleGetTriageContext,
} from './triageTools.js';
import {
  listAccountsDef, handleListAccounts,
  addAccountDef, handleAddAccount,
  updateAccountSettingsDef, handleUpdateAccountSettings,
  testAccountConnectionDef, handleTestAccountConnection,
  createAliasDef, handleCreateAlias,
  updateAliasDef, handleUpdateAlias,
  deleteAliasDef, handleDeleteAlias,
  listRulesDef, handleListRules,
  createRuleDef, handleCreateRule,
  updateRuleDef, handleUpdateRule,
  deleteRuleDef, handleDeleteRule,
  runRulesDef, handleRunRules,
} from './accountTools.js';

// TOOL_DEFS drives tools/list; HANDLERS drives tools/call. Slices 09 and 10
// append to both. Keep names, descriptions, and inputSchema field names verbatim
// from internal/mcp/server.go (README D6: id-bearing fields diverge to strings).
export const TOOL_DEFS = [
  {
    name: 'ping',
    description: 'Health check: returns {"pong":true}. Proves transport + auth round-trip.',
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
    inputSchema: { type: 'object', properties: {} },
  },
  searchMetadataDef,
  searchMessageBodiesDef,
  semanticSearchMessagesDef,
  getMessageDef,
  listMessagesDef,
  getStatsDef,
  aggregateDef,
  searchByDomainsDef,
  findSimilarMessagesDef,
  searchInMessageDef,
  stageDeletionDef,
  createDraftDef,
  updateDraftDef,
  listDraftsDef,
  getDraftDef,
  deleteDraftDef,
  sendEmailDef,
  sendDraftDef,
  unsendEmailDef,
  listOutboxDef,
  recallEmailDef,
  replyEmailDef,
  replyAllEmailDef,
  forwardEmailDef,
  listFoldersDef,
  createFolderDef,
  renameFolderDef,
  deleteFolderDef,
  moveMessagesDef,
  archiveMessagesDef,
  trashMessagesDef,
  markReadDef,
  markUnreadDef,
  starMessageDef,
  unstarMessageDef,
  markSpamDef,
  markNotSpamDef,
  snoozeMessageDef,
  unsnoozeMessageDef,
  setCategoryDef,
  gtdClassifyDef,
  gtdDoneDef,
  markTriagedDef,
  triageInboxDef,
  getTriageContextDef,
  listAccountsDef,
  addAccountDef,
  updateAccountSettingsDef,
  testAccountConnectionDef,
  createAliasDef,
  updateAliasDef,
  deleteAliasDef,
  listRulesDef,
  createRuleDef,
  updateRuleDef,
  deleteRuleDef,
  runRulesDef,
];

// Name → required scope. Keep this map separate from TOOL_DEFS because those
// definitions are serialized verbatim onto the tools/list wire response.
export const TOOL_SCOPES = {
  ping: 'read',
  search_metadata: 'read',
  search_message_bodies: 'read',
  semantic_search_messages: 'read',
  get_message: 'read',
  list_messages: 'read',
  get_stats: 'read',
  aggregate: 'read',
  search_by_domains: 'read',
  find_similar_messages: 'read',
  search_in_message: 'read',
  stage_deletion: 'write',
  create_draft: 'write',
  update_draft: 'write',
  list_drafts: 'read',
  get_draft: 'read',
  delete_draft: 'write',
  send_email: 'send',
  send_draft: 'send',
  unsend_email: 'send',
  list_outbox: 'read',
  recall_email: 'send',
  reply_email: 'send',
  reply_all_email: 'send',
  forward_email: 'send',
  list_folders: 'read',
  create_folder: 'write',
  rename_folder: 'write',
  delete_folder: 'write',
  move_messages: 'write',
  archive_messages: 'write',
  trash_messages: 'write',
  mark_read: 'write',
  mark_unread: 'write',
  star_message: 'write',
  unstar_message: 'write',
  mark_spam: 'write',
  mark_not_spam: 'write',
  snooze_message: 'write',
  unsnooze_message: 'write',
  set_category: 'write',
  gtd_classify: 'write',
  gtd_done: 'write',
  mark_triaged: 'write',
  triage_inbox: 'read',
  get_triage_context: 'read',
  list_accounts: 'read',
  add_account: 'settings',
  update_account_settings: 'settings',
  test_account_connection: 'settings',
  create_alias: 'settings',
  update_alias: 'settings',
  delete_alias: 'settings',
  list_rules: 'settings',
  create_rule: 'settings',
  update_rule: 'settings',
  delete_rule: 'settings',
  run_rules: ['settings', 'write'],
};

export const HANDLERS = {
  // eslint-disable-next-line no-unused-vars
  ping: async (_args, _scope) => jsonResult({ pong: true }),
  search_metadata: (a, s) => handleSearchMetadata(a, s),
  search_message_bodies: (a, s) => handleSearchMessageBodies(a, s),
  semantic_search_messages: (a, s) => handleSemanticSearchMessages(a, s),
  get_message: (a, s) => handleGetMessage(a, s),
  list_messages: (a, s) => handleListMessages(a, s),
  get_stats: (a, s) => handleGetStats(a, s),
  aggregate: (a, s) => handleAggregate(a, s),
  search_by_domains: (a, s) => handleSearchByDomains(a, s),
  find_similar_messages: (a, s) => handleFindSimilarMessages(a, s),
  search_in_message: (a, s) => handleSearchInMessage(a, s),
  stage_deletion: (a, s) => handleStageDeletion(a, s),
  create_draft: handleCreateDraft,
  update_draft: handleUpdateDraft,
  list_drafts: handleListDrafts,
  get_draft: handleGetDraft,
  delete_draft: handleDeleteDraft,
  send_email: handleSendEmail,
  send_draft: handleSendDraft,
  unsend_email: handleUnsendEmail,
  list_outbox: handleListOutbox,
  recall_email: handleRecallEmail,
  reply_email: handleReplyEmail,
  reply_all_email: handleReplyAllEmail,
  forward_email: handleForwardEmail,
  list_folders: handleListFolders,
  create_folder: handleCreateFolder,
  rename_folder: handleRenameFolder,
  delete_folder: handleDeleteFolder,
  move_messages: handleMoveMessages,
  archive_messages: handleArchiveMessages,
  trash_messages: handleTrashMessages,
  mark_read: handleMarkRead,
  mark_unread: handleMarkUnread,
  star_message: handleStarMessage,
  unstar_message: handleUnstarMessage,
  mark_spam: handleMarkSpam,
  mark_not_spam: handleMarkNotSpam,
  snooze_message: handleSnoozeMessage,
  unsnooze_message: handleUnsnoozeMessage,
  set_category: handleSetCategory,
  gtd_classify: handleGtdClassify,
  gtd_done: handleGtdDone,
  mark_triaged: handleMarkTriaged,
  triage_inbox: handleTriageInbox,
  get_triage_context: handleGetTriageContext,
  list_accounts: handleListAccounts,
  add_account: handleAddAccount,
  update_account_settings: handleUpdateAccountSettings,
  test_account_connection: handleTestAccountConnection,
  create_alias: handleCreateAlias,
  update_alias: handleUpdateAlias,
  delete_alias: handleDeleteAlias,
  list_rules: handleListRules,
  create_rule: handleCreateRule,
  update_rule: handleUpdateRule,
  delete_rule: handleDeleteRule,
  run_rules: handleRunRules,
};
