#!/usr/bin/env python3
"""
Self-host every Google font the MailFlow UI uses, so the app makes no external font
requests at runtime.

Reads the query manifest (scripts/fonts.manifest), fetches Google's css2 for each with a
browser User-Agent (to get woff2 + per-subset @font-face), downloads every referenced
woff2 into frontend/public/fonts/, descriptor-dedups the @font-face blocks, prunes any
orphaned woff2, and writes public/fonts/fonts.css with src rewritten to same-origin
/fonts/. index.html loads that stylesheet; fonts.js only swaps CSS variables.

Re-run after editing the manifest (e.g. adding a font set) to regenerate the assets.
Safe: aborts without touching files if the fetch yields an implausibly small result.
"""
import re, os, time, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "frontend"))
OUT_DIR = os.path.join(ROOT, "public", "fonts")
CSS_OUT = os.path.join(OUT_DIR, "fonts.css")
MANIFEST = os.path.join(HERE, "fonts.manifest")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

HEADER = ("/* Self-hosted fonts for MailFlow - generated by scripts/selfhost-fonts.py,\n"
          "   do not hand-edit. Mirrors Google Fonts css2 for the exact families/weights/\n"
          "   subsets the app uses, src rewritten to same-origin /fonts/. No external requests. */\n\n")

os.makedirs(OUT_DIR, exist_ok=True)
queries = [ln.strip() for ln in open(MANIFEST, encoding="utf-8")
           if ln.strip() and not ln.lstrip().startswith("#")]
queries = list(dict.fromkeys(queries))
print(f"manifest queries: {len(queries)}")

def http_get(url, text=False, tries=5):
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=30) as r:
                data = r.read()
            return data.decode("utf-8") if text else data
        except Exception:
            if attempt == tries - 1:
                raise
            time.sleep(2 * (attempt + 1))   # backoff on transient/rate-limit errors

def field(block, name):
    m = re.search(rf"{name}:\s*([^;]+);", block)
    return m.group(1).strip() if m else ""

gstatic_re = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)")
face_re = re.compile(r"(?:/\*[^*]*\*/\s*)?@font-face\s*\{[^}]*\}", re.S)

ref_files, blocks, seen_desc, subsets = {}, [], set(), {}
for i, q in enumerate(queries, 1):
    css = http_get(f"https://fonts.googleapis.com/css2?{q}&display=swap", text=True)
    n = 0
    for m in face_re.finditer(css):
        block = m.group(0)
        um = gstatic_re.search(block)
        if not um:
            continue
        parts = um.group(1).split("/s/")[1].split("/")
        local_rel = f"{parts[0]}/{parts[-1]}"
        rewritten = gstatic_re.sub(f"url(/fonts/{local_rel})", block).strip()
        # Dedup by rendering descriptor, not file: variable fonts return different file
        # instances for the same family/weight/style/range across query syntaxes.
        desc = (field(block, "font-family"), field(block, "font-weight"),
                field(block, "font-style"), field(block, "unicode-range"))
        if desc in seen_desc:
            continue
        seen_desc.add(desc)
        blocks.append(rewritten)
        ref_files[local_rel] = um.group(1)
        lab = re.match(r"/\*\s*([^*]+?)\s*\*/", block)
        if lab:
            subsets[lab.group(1)] = subsets.get(lab.group(1), 0) + 1
        n += 1
    print(f"  [{i}/{len(queries)}] {q[:44]}... -> {n}")

print(f"\n@font-face blocks: {len(blocks)} | referenced files: {len(ref_files)}")
print("subsets:", subsets)

# Safety: never write/prune on an implausibly small parse (e.g. all fetches failed).
if len(blocks) < 500:
    raise SystemExit(f"ABORT: only {len(blocks)} blocks parsed (expected ~860). "
                     "Fetches likely failed. Not touching files or fonts.css.")

# Download referenced files (idempotent)
dl = 0
for local_rel, url in ref_files.items():
    dest = os.path.join(OUT_DIR, local_rel)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        continue
    open(dest, "wb").write(http_get(url)); dl += 1

# Write CSS, then prune orphans
open(CSS_OUT, "w", encoding="utf-8").write(HEADER + "\n".join(blocks) + "\n")
pruned = 0
for root, _, fnames in os.walk(OUT_DIR):
    for fn in fnames:
        if fn.endswith(".woff2") and \
           os.path.relpath(os.path.join(root, fn), OUT_DIR) not in ref_files:
            os.remove(os.path.join(root, fn)); pruned += 1
for d in list(os.listdir(OUT_DIR)):
    dp = os.path.join(OUT_DIR, d)
    if os.path.isdir(dp) and not os.listdir(dp):
        os.rmdir(dp)

print(f"downloaded: {dl} | pruned: {pruned} | fonts.css: {os.path.getsize(CSS_OUT)//1024} KB")
